source/otzovik/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
        ReviewCreateView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('products/<int:pk>/', ProductView.as_view(), name='product_detail'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('review/<int:pk>/add/', ReviewCreateView.as_view(), name='review_create'),
]

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

CATEGORY_CHOICES = (
    ('other', 'Другое'),
    ('food', 'Еда'),
    ('clothes', 'Одежда'),
    ('household', 'Товары для дома'),
)

class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name='Товар')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name='Категория')
    desctiption= models.TextField(max_length=3000,null=True, blank=True, verbose_name='Описание' )
    photo = models.ImageField(upload_to='product_images', null=True, blank=True, verbose_name='Фото')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

REVIEW_CHOICES = (
    (5, 'отлично'),
    (4, 'хорошо'),
    (3, 'удовлетворительно'),
    (2, 'плохо'),
    (1, 'отвратительно')
)

class Review(models.Model):
    product = models.ForeignKey('webapp.Product', related_name='review',
                                on_delete=models.CASCADE, verbose_name='Товар')
    author = models.ForeignKey(User, null=True, blank=True, default=None, verbose_name='Автор',
                               on_delete=models.CASCADE, related_name='review')
    text = models.TextField(max_length=400, verbose_name='Текст отзыва')
    raiting = models.IntegerField(choices=REVIEW_CHOICES, verbose_name='Оценка', null=True, blank=False)

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Product, Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['text', 'raiting']

source/webapp/views.py
from django.shortcuts import reverse, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.models import Product, Review
from webapp.forms import ReviewForm

class IndexView(ListView):
    model = Product
    template_name = 'index.html'

class ProductView(DetailView):
    model = Product
    template_name = 'product/detail.html'


class ProductCreateView(CreateView):
    model = Product
    template_name = 'product/create.html'
    fields = ('name', 'category', 'desctiption', 'photo')
    success_url = reverse_lazy('webapp:index')


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'product/update.html'
    fields = ('name', 'category', 'desctiption', 'photo')
    context_object_name = 'product'

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class ProductDeleteView(DeleteView):
    template_name = 'product/delete.html'
    success_url = reverse_lazy('webapp:index')
    model = Product
    context_object_name = 'product'


class ReviewCreateView(CreateView):
    template_name = 'review/review_create.html'
    form_class = ReviewForm

    def form_valid(self, form):
        user = self.request.user
        product_pk = self.kwargs.get('pk')
        product = get_object_or_404(Product, pk=product_pk)
        product.review.create(author=user, **form.cleaned_data)
        return redirect('webapp:product_detail', pk=product_pk)

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'webapp:index' %}" class="nav-link">На главную</a></li>
            {% block menu %}{% endblock %}
        </ul>
{#        <ul class="navbar-nav ml-auto">#}
{#            <li class="nav-item"><a href="{% url 'webapp:basket' %}" class="nav-link">#}
{#                Корзина ({{ request.session.products_count|default:0 }})#}
{#            </a></li>#}
{#            {% if request.user.is_authenticated %}#}
{#                <li class="nav-item"><a href="{% url 'accounts:detail' request.user.pk %}" class="nav-link">#}
{#                    Привет, {{ request.user.username }}!#}
{#                </a></li>#}
{#                <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Выход</a></li>#}
{#            {% else %}#}
{#                <li class="nav-item"><a href="{% url 'accounts:create' %}" class="nav-link">Регистрация</a></li>#}
{#                <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link">Вход</a></li>#}
{#            {% endif %}#}
{#        </ul>#}
    </div>
</nav>
<div class="container mt-3 mb-3">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Товары{% endblock %}
{% block menu %}
    <li class="nav-item"><a href="{% url 'webapp:product_create' %}" class="nav-link">Добавить товар</a></li>
{#    <li class="nav-item"><a href="{% url 'webapp:review_create' %}" class="nav-link">Добавить отзыв к товару</a></li>#}
{% endblock %}
{% block content %}
    <h1 class="text-center">Товары</h1>
    <div class="row">
        {% for product in product_list %}
            <div class="col col-3">
                <div class="card">
                    {% if product.photo %}
                        <img src="{{ product.photo.url }}" alt="prod_pic" class="img-fluid">
                    {% else %}
                        <img src="{% static 'image.jpg' %}" alt="prod_pic" class="img-fluid">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.get_category_display }}</p>
                        <a href="{% url "webapp:product_detail" product.pk %}"
                           class="btn btn-primary mb-3">Посмотреть</a>
                        <a href="{% url 'webapp:product_update' product.pk %}" class="btn btn-primary mb-3">Редактировать товар</a>
                        <a href="{% url 'webapp:product_delete' product.pk %}" class="btn btn-primary">Удалить товар</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/partial/form.html
{% load widget_tweaks %}
{% csrf_token %}
{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}
{% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}" class="mr-3">{{ field.label }}</label>
        {% if field|field_type == 'imagefield' or field|field_type == 'filefield' %}
            {{ field }}
        {% else %}
            {{ field|add_class:"form-control" }}
        {% endif %}
        {% for error in field.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
{% endfor %}

source/webapp/templates/product/create.html
{% extends 'base.html' %}
{% block title %}Добавить товар{% endblock %}
{% block content %}
    <h1 class="text-center">Создать товар</h1>
    <form action="{% url "webapp:product_create" %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Создать" class="btn btn-primary">
    </form>
{% endblock %}

source/webapp/templates/product/delete.html
{% extends 'base.html' %}

{% block title %}Удалить продукт{% endblock %}



{% block content %}
    <h1>Вы уверены, что хотите удалить продукт  {{ product }}?</h1>
    <form method="POST" action="{% url 'webapp:product_delete' product.pk %}" class="text-center">
        {% csrf_token %}
        <p><input type="submit" value="ПОДТВЕРДИТЬ" class="btn btn-danger"></p>
        <p><a href="{% url 'webapp:index' %}" class="btn btn-dark">ОТМЕНА</a></p>
    </form>
{% endblock %}

source/webapp/templates/product/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
    <div class="text-center">
        <h1>{{ product.name }}</h1>
        <div class="row">
            <div class="col col-12 col-sm-10 col-md-8 col-lg-6 m-auto">
                {% if product.photo %}
                    <img src="{{ product.photo.url }}" alt="prod_pic" class="img-fluid">
                {% else %}
                    <img src="{% static 'image.jpg' %}" alt="prod_pic" class="img-fluid">
                {% endif %}
            </div>
        </div>
        <p><b>Категория:</b> {{ product.get_category_display }}</p>
        <p><b>Описание товара: <br></b> {{ product.desctiption }}</p>

        {% if request.user.is_authenticated %}
            <a href="{% url 'webapp:review_create' product.pk %}" class="btn btn-primary">Добавить отзыв к товару</a>
        {% endif %}
    </div>
{% endblock %}

source/webapp/templates/product/update.html
{% extends 'base.html' %}
{% block title %}Редактировать товар{% endblock %}
{% block content %}
    <h1 class="text-center">Редактировать товар</h1>
    <form action="{% url "webapp:product_update" product.pk%}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Редактировать" class="btn btn-primary">
    </form>
{% endblock %}

source/webapp/templates/review/review_create.html
{% extends "base.html" %}
{% block title %}Добавить отзыв к товару{% endblock %}
{% block content %}
   <h1>Добавить отзыв к товару</h1>
   <form action="" method="POST">
        {% include 'partial/form.html' with button_text='Создать' %}
        <p><input type="submit" value="Создать" class="btn-lg btn-dark"></p>
   </form>
{% endblock %}